/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.laywer1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ΜΑΡΙΝΟΣ
 */
public class Diathesimes_Formes extends javax.swing.JFrame {
Connection con1 ;
        PreparedStatement pst;
        ResultSet rs;
    int  mousepX,mousepY;
    public Diathesimes_Formes() {
        initComponents();
        getListaFormes();
    }
    
     private void getListaFormes()
   {
    int c;
     try {
            Class.forName("java.sql.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            pst = con1.prepareStatement("select * from formes_ep ");
            
           ResultSet rs = pst.executeQuery();
           ResultSetMetaData Rss = rs.getMetaData();
           c = Rss.getColumnCount();
           
           DefaultTableModel Df = (DefaultTableModel)Formes.getModel();
           Df.setRowCount(0);
           
           while(rs.next())
           {
               Vector v2 = new Vector();
               
               for(int a=1; a<=c; a++)
               {
                v2.add(rs.getString("imerominia"));
                       v2.add(rs.getString("dikaio"));
                           v2.add(rs.getString("yp_pel"));
                   }
              Df.addRow(v2);
                }
         } 
          catch (ClassNotFoundException ex) {
            Logger.getLogger(Diathesimes_Formes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger(Diathesimes_Formes.class.getName()).log(Level.SEVERE, null, ex);
         }
    
    
    
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        GetPlirofYp = new javax.swing.JButton();
        GetPlirofPel = new javax.swing.JButton();
        Prosthese = new javax.swing.JButton();
        DeleteForma = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Formes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("E-LAWYER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/icons8_back_arrow_50px_2.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 490, -1, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/icons8_exit_50px.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/Logo-3.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, -10, -1, 240));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Διαθέσιμες Φόρμες");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        GetPlirofYp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GetPlirofYp.setText("Πληροφορίες");
        GetPlirofYp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetPlirofYpActionPerformed(evt);
            }
        });
        jPanel1.add(GetPlirofYp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 150, 40));

        GetPlirofPel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GetPlirofPel.setText("Στοιχεία Πελάτη");
        GetPlirofPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetPlirofPelActionPerformed(evt);
            }
        });
        jPanel1.add(GetPlirofPel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, 40));

        Prosthese.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Prosthese.setText("Αποδοχή");
        Prosthese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProstheseMouseClicked(evt);
            }
        });
        Prosthese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProstheseActionPerformed(evt);
            }
        });
        jPanel1.add(Prosthese, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, -1, 40));

        DeleteForma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DeleteForma.setText("Απόρριψη");
        DeleteForma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteFormaMouseClicked(evt);
            }
        });
        jPanel1.add(DeleteForma, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, -1, 40));

        Formes.setAutoCreateRowSorter(true);
        Formes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ημερομηνία Καταχώρησης", "Δίκαιο", "Username(Υποψήφιου Πελάτη)"
            }
        ));
        Formes.setSelectionBackground(new java.awt.Color(0, 51, 204));
        jScrollPane1.setViewportView(Formes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 570, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
         int aX = evt.getXOnScreen();
        int aY = evt.getYOnScreen();
        
        this.setLocation(aX-mousepX,aY-mousepY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
           mousepX = evt.getX();
         mousepY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
       this.dispose();
        Dikigoriko_Grafeio m = new Dikigoriko_Grafeio();
        m.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void GetPlirofYpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetPlirofYpActionPerformed
         DefaultTableModel Df = (DefaultTableModel) Formes.getModel();
         int selectedIndex =  Formes.getSelectedRow();  
           String pelatis = Formes.getModel().getValueAt(selectedIndex, 2).toString();
            String dikaio= Formes.getModel().getValueAt(selectedIndex, 1).toString();
         PliroforiesFormes m = new  PliroforiesFormes(pelatis);
        m.setVisible(true);
    }//GEN-LAST:event_GetPlirofYpActionPerformed

    private void ProstheseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProstheseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProstheseActionPerformed

    private void GetPlirofPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetPlirofPelActionPerformed
        DefaultTableModel Df = (DefaultTableModel) Formes.getModel();
         int selectedIndex =  Formes.getSelectedRow();  
           String pelatis = Formes.getModel().getValueAt(selectedIndex, 2).toString();
         PliroforiesPel m = new  PliroforiesPel(pelatis);
        m.setVisible(true);
    }//GEN-LAST:event_GetPlirofPelActionPerformed

    private void ProstheseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProstheseMouseClicked
     DefaultTableModel Df = (DefaultTableModel)Formes.getModel();
         int selectedIndex = Formes.getSelectedRow();
         DefaultComboBoxModel model = null;
         
        this.dispose();
        Create_Yp m = new Create_Yp();
        m.setVisible(true);
    }//GEN-LAST:event_ProstheseMouseClicked

    private void DeleteFormaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteFormaMouseClicked
        DefaultTableModel Df = (DefaultTableModel) Formes.getModel();
         int selectedIndex =  Formes.getSelectedRow();
         
          try {
             
             String pelatis = Formes.getModel().getValueAt(selectedIndex, 2).toString();
             String dikaio = Formes.getModel().getValueAt(selectedIndex, 1).toString();
            
              int dialogResult = JOptionPane.showConfirmDialog(null,"Θέλετε να απορρίψετε την υπόθεση?","Warning",JOptionPane.YES_NO_OPTION);
              
              if(dialogResult == JOptionPane.YES_OPTION)
              {   
        
             Class.forName("java.sql.Driver");
             
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            pst = con1.prepareStatement("delete from formes_ep where yp_pel=? and dikaio=? ");
            pst.setString(1, pelatis);
            pst.setString (2,dikaio);
            
        
            
            pst.executeUpdate();
            
           JOptionPane.showMessageDialog(this,"H υπόθεση απορρίφθηκε");
           
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            pst = con1.prepareStatement("delete from pelatis where username_pelatis=?  ");
            pst.setString(1, pelatis);
           pst.executeUpdate();
            
           getListaFormes(); 
            
            
        } 
          }   
               
         catch (ClassNotFoundException ex) {
            Logger.getLogger(Diathesimes_Formes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger(Diathesimes_Formes.class.getName()).log(Level.SEVERE, null, ex);
         } 
    }//GEN-LAST:event_DeleteFormaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diathesimes_Formes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diathesimes_Formes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diathesimes_Formes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diathesimes_Formes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diathesimes_Formes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteForma;
    private javax.swing.JTable Formes;
    private javax.swing.JButton GetPlirofPel;
    private javax.swing.JButton GetPlirofYp;
    private javax.swing.JButton Prosthese;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
