/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.laywer1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ΜΑΡΙΝΟΣ
 */
public class Forma_Ep extends javax.swing.JFrame {
 Connection con1 ;
        PreparedStatement pst;
        ResultSet rs;
     int  mousepX,mousepY;
    public Forma_Ep(String username) {
        initComponents();
         user.setText(username);
       user.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_perigrafi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        SendYp = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_antidikos = new javax.swing.JTextField();
        CBdikaio = new javax.swing.JComboBox<>();
        user = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Φόρμα Υπόθεσης");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 25, 338, 50));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Αντίστοιχο Δίκαιο:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 235, 61));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Περιγραφή Υπόθεσης :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 283, 67));
        jPanel1.add(txt_perigrafi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 475, 160));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/Logo-3.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 25, -1, -1));

        SendYp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/icons8_check_file_70px.png"))); // NOI18N
        SendYp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SendYpMouseClicked(evt);
            }
        });
        jPanel1.add(SendYp, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/icons8_exit_50px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/icons8_back_arrow_50px_2.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 620, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Αντίδικος :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        txt_antidikos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_antidikosActionPerformed(evt);
            }
        });
        jPanel1.add(txt_antidikos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 370, 40));

        CBdikaio.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CBdikaio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Χωρίς Επιλογή", "Αστικό", "Εμπορικό", "Ποινικό" }));
        jPanel1.add(CBdikaio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, 40));

        user.setText("jLabel1");
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
          System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
         this.dispose();
        Register_Page m = new  Register_Page();
        m.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void txt_antidikosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_antidikosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_antidikosActionPerformed

    private void SendYpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendYpMouseClicked
          String dikaio = CBdikaio.getSelectedItem().toString();
        String perigrafi = txt_perigrafi.getText();
        String antidikos = txt_antidikos.getText();
        String pelatis = user.getText();
      
           if (perigrafi.equals("") || antidikos.equals("") || dikaio.equals("Χωρίς Δίκαιο") )
            {
             JOptionPane.showMessageDialog(null,"Συμπληρώστε τα Στοιχεία","Error",JOptionPane.ERROR_MESSAGE);
             txt_perigrafi.setText("");
             txt_antidikos.setText("");
            }
           
             
              
            try {
            Class.forName("java.sql.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            java.util.Date date=new java.util.Date();
			
			java.sql.Date sqlDate=new java.sql.Date(date.getTime());
            pst = con1.prepareStatement("insert into formes_ep(dikaio,perigrafi,yp_pel,antidikos,imerominia)values(?,?,?,?,?)");
           
            pst.setString(1, dikaio);
            pst.setString(2, perigrafi);
            pst.setString(3, pelatis);
            pst.setString(4, antidikos);
            pst.setDate(5,sqlDate);
            pst.executeUpdate();
            
           
            
           JOptionPane.showMessageDialog(this,"Η Υπόθεση στάλθηκε στο γραφείο");
            System.exit(0);
           
        } 
             catch (ClassNotFoundException ex) {
            Logger.getLogger(Forma_Ep.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger(Forma_Ep.class.getName()).log(Level.SEVERE, null, ex);
    }//GEN-LAST:event_SendYpMouseClicked
    }
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forma_Ep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forma_Ep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forma_Ep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forma_Ep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forma_Ep("user").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBdikaio;
    private javax.swing.JLabel SendYp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_antidikos;
    private javax.swing.JTextField txt_perigrafi;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
