/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.laywer1;



import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ΜΑΡΙΝΟΣ
 */
public class Lista_Pelatwn extends javax.swing.JFrame {

    Connection con1 ;
        PreparedStatement pst;
        ResultSet rs;
    int  mousepX,mousepY;
    public Lista_Pelatwn() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        getPlirofPel = new javax.swing.JButton();
        GetPlirofOf = new javax.swing.JButton();
        CreateOf = new javax.swing.JButton();
        DeletePel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista_Pelatwn = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        getLista_Pel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("E-LAWYER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/icons8_back_arrow_50px_2.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 490, -1, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/icons8_exit_50px.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/Logo-3.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, 240));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Λίστα Πελατών");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        getPlirofPel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getPlirofPel.setText("Πληροφορίες");
        getPlirofPel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getPlirofPelMouseClicked(evt);
            }
        });
        getPlirofPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPlirofPelActionPerformed(evt);
            }
        });
        jPanel1.add(getPlirofPel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 150, 40));

        GetPlirofOf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GetPlirofOf.setText("Προβολή Οφειλών");
        GetPlirofOf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GetPlirofOfMouseClicked(evt);
            }
        });
        jPanel1.add(GetPlirofOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, 40));

        CreateOf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CreateOf.setText("Δημιουργία Οφειλής");
        CreateOf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateOfMouseClicked(evt);
            }
        });
        jPanel1.add(CreateOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, 40));

        DeletePel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DeletePel.setText("Διαγραφή");
        DeletePel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletePelActionPerformed(evt);
            }
        });
        jPanel1.add(DeletePel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, -1, 40));

        Lista_Pelatwn.setAutoCreateRowSorter(true);
        Lista_Pelatwn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Επώνυμο", "Όνομα", "Πόλη", "Username"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Lista_Pelatwn.setSelectionBackground(new java.awt.Color(0, 51, 204));
        Lista_Pelatwn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lista_PelatwnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Lista_Pelatwn);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 530, 190));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Πρώτο Γράμμα Επιθέτου:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- -", "Α", "Β", "Γ", "Δ", "Ε", "Ζ", "Η", "Θ", "Ι", "Κ", "Λ", "Μ", "Ν", "Ξ", "Ο", "Π", "Ρ", "Σ", "Τ", "Υ", "Φ", "Χ", "Ψ", "Ω" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        getLista_Pel.setText("Αναζήτηση");
        getLista_Pel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getLista_PelActionPerformed(evt);
            }
        });
        jPanel1.add(getLista_Pel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
         int aX = evt.getXOnScreen();
        int aY = evt.getYOnScreen();
        
        this.setLocation(aX-mousepX,aY-mousepY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
           mousepX = evt.getX();
         mousepY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
       this.dispose();
        Dikigoriko_Grafeio m = new Dikigoriko_Grafeio();
        m.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void getPlirofPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPlirofPelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getPlirofPelActionPerformed

    private void CreateOfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateOfMouseClicked
  DefaultTableModel Df = (DefaultTableModel) Lista_Pelatwn.getModel();
         int selectedIndex =  Lista_Pelatwn.getSelectedRow();
          String pelatis = Lista_Pelatwn.getModel().getValueAt(selectedIndex, 4).toString();
        this.dispose();
         Create_Of m = new  Create_Of(pelatis);
        m.setVisible(true);
    }//GEN-LAST:event_CreateOfMouseClicked

    private void getLista_PelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getLista_PelActionPerformed
      int c;
       String letter = jComboBox1.getSelectedItem().toString();
           try {
            Class.forName("java.sql.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            pst = con1.prepareStatement("select * from pelatis where Left(epwnimo_pel,1)= ? ");
          pst.setString(1, letter);
            
           ResultSet rs = pst.executeQuery();
           ResultSetMetaData Rss = rs.getMetaData();
           c = Rss.getColumnCount();
           
           DefaultTableModel Df = (DefaultTableModel)Lista_Pelatwn.getModel();
           Df.setRowCount(0);
           
           while(rs.next())
           {
               Vector v2 = new Vector();
               
               for(int a=1; a<=c; a++)
               {
                v2.add(rs.getString("id_pel"));
                   v2.add(rs.getString("epwnimo_pel"));
                       v2.add(rs.getString("onoma_pel"));
                           v2.add(rs.getString("city"));
                            v2.add(rs.getString("username_pelatis"));
                   }
              Df.addRow(v2);
                }
         } 
          catch (ClassNotFoundException ex) {
            Logger.getLogger(Lista_Pelatwn.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger(Lista_Pelatwn.class.getName()).log(Level.SEVERE, null, ex);
         }
        
         
         
    }//GEN-LAST:event_getLista_PelActionPerformed

    private void table_update()
    {
        int c;
          String letter = (String)jComboBox1.getSelectedItem().toString();
           try {
            Class.forName("java.sql.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            pst = con1.prepareStatement("select * from pelatis where Left(epwnimo_pel,1)= ? ");
            pst.setString(1, letter);
            
           ResultSet rs = pst.executeQuery();
           ResultSetMetaData Rss = rs.getMetaData();
           c = Rss.getColumnCount();
           
           DefaultTableModel Df = (DefaultTableModel)Lista_Pelatwn.getModel();
           Df.setRowCount(0);
           
           
           while(rs.next())
           {
               Vector v2 = new Vector();
               
               for(int a=1; a<=c; a++)
               {
                
                   v2.add(rs.getString("id"));
                       v2.add(rs.getString("epwnimo_pel"));
                           v2.add(rs.getString("onoma_pel"));
                               v2.add(rs.getString("city"));
                                v2.add(rs.getString("username_pelatis"));
                   }
              Df.addRow(v2);
               
           }
         
                 
            
        
        } 
           
               
         catch (ClassNotFoundException ex) {
            Logger.getLogger(Lista_Pelatwn.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger(Lista_Pelatwn.class.getName()).log(Level.SEVERE, null, ex);
         } 
           
      }
    
    
    
    
    
    
    
    
    
    
    private void Lista_PelatwnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lista_PelatwnMouseClicked
        DefaultTableModel Df = (DefaultTableModel)Lista_Pelatwn.getModel();
         int selectedIndex = Lista_Pelatwn.getSelectedRow();
        
    }//GEN-LAST:event_Lista_PelatwnMouseClicked

    private void DeletePelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletePelActionPerformed
        // TODO add your handling code here:
         DefaultTableModel Df = (DefaultTableModel) Lista_Pelatwn.getModel();
         int selectedIndex =  Lista_Pelatwn.getSelectedRow();
         
          try {
             
              int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
            
              int dialogResult = JOptionPane.showConfirmDialog(null,"Θέλετε να διαγράψετε τον πελάτη?","Warning",JOptionPane.YES_NO_OPTION);
              
              if(dialogResult == JOptionPane.YES_OPTION)
              {   
        
             Class.forName("java.sql.Driver");
             
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            pst = con1.prepareStatement("delete from pelatis where id_pel=? ");
            
            pst.setInt(1,id );
            
            pst.executeUpdate();
            
           JOptionPane.showMessageDialog(this,"Ο πελάτης διαγράφηκε");
            
            table_update(); 
            
            
        } 
          }   
               
         catch (ClassNotFoundException ex) {
            Logger.getLogger(Lista_Pelatwn.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger(Lista_Pelatwn.class.getName()).log(Level.SEVERE, null, ex);
         } 
    }//GEN-LAST:event_DeletePelActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void GetPlirofOfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GetPlirofOfMouseClicked
        DefaultTableModel Df = (DefaultTableModel) Lista_Pelatwn.getModel();
         int selectedIndex =  Lista_Pelatwn.getSelectedRow();
          String pelatis = Lista_Pelatwn.getModel().getValueAt(selectedIndex, 4).toString();
        this.dispose();
         Provoli_Ofeilwn m = new  Provoli_Ofeilwn(pelatis);
        m.setVisible(true);
    }//GEN-LAST:event_GetPlirofOfMouseClicked

    private void getPlirofPelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getPlirofPelMouseClicked
  DefaultTableModel Df = (DefaultTableModel) Lista_Pelatwn.getModel();
         int selectedIndex =  Lista_Pelatwn.getSelectedRow();  
           String pelatis = Lista_Pelatwn.getModel().getValueAt(selectedIndex, 4).toString();
         PliroforiesPel m = new  PliroforiesPel(pelatis);
        m.setVisible(true);
    }//GEN-LAST:event_getPlirofPelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lista_Pelatwn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lista_Pelatwn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lista_Pelatwn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lista_Pelatwn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lista_Pelatwn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateOf;
    private javax.swing.JButton DeletePel;
    private javax.swing.JButton GetPlirofOf;
    private javax.swing.JTable Lista_Pelatwn;
    private javax.swing.JButton getLista_Pel;
    private javax.swing.JButton getPlirofPel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
