/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.laywer1;

import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ΜΑΡΙΝΟΣ
 */
public class Lista_Dikigorwn extends javax.swing.JFrame {
Connection con1 ;
        PreparedStatement pst;
        ResultSet rs;
    int  mousepX,mousepY;
    public Lista_Dikigorwn() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        DeleteDik = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista_Dikigorwn = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        GetListaDik = new javax.swing.JLabel();
        dikigoros = new javax.swing.JLabel();
        check = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("E-LAWYER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/icons8_back_arrow_50px_2.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 490, -1, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/icons8_exit_50px.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/Logo-3.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, 240));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Λίστα Δικηγόρων");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Πληροφορίες");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 150, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Έλεγχος Επίδοσης");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Πληρωμή");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, -1, 40));

        DeleteDik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DeleteDik.setText("Διαγραφή");
        DeleteDik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteDikMouseClicked(evt);
            }
        });
        jPanel1.add(DeleteDik, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, -1, 40));

        Lista_Dikigorwn.setAutoCreateRowSorter(true);
        Lista_Dikigorwn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "Επώνυμο", "Όνομα"
            }
        ));
        Lista_Dikigorwn.setSelectionBackground(new java.awt.Color(0, 51, 204));
        Lista_Dikigorwn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lista_DikigorwnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Lista_Dikigorwn);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 480, 190));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Αναζήτηση Ανά Δίκαιο:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- - - -", "Εμπορικό", "Αστικό", "Ποινικό" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 80, -1));

        GetListaDik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/icons8_search_40px.png"))); // NOI18N
        GetListaDik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GetListaDikMouseClicked(evt);
            }
        });
        jPanel1.add(GetListaDik, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));
        jPanel1.add(dikigoros, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 240, 100, 30));
        jPanel1.add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 300, 70, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
         int aX = evt.getXOnScreen();
        int aY = evt.getYOnScreen();
        
        this.setLocation(aX-mousepX,aY-mousepY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
           mousepX = evt.getX();
         mousepY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
       this.dispose();
        Dikigoriko_Grafeio m = new Dikigoriko_Grafeio();
        m.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
     
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void Lista_DikigorwnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lista_DikigorwnMouseClicked
          DefaultTableModel Df = (DefaultTableModel)Lista_Dikigorwn.getModel();
         int selectedIndex = Lista_Dikigorwn.getSelectedRow();
    }//GEN-LAST:event_Lista_DikigorwnMouseClicked

    private void GetListaDikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GetListaDikMouseClicked
   int c;
         String dikaio = jComboBox1.getSelectedItem().toString();
       
           try {
            Class.forName("java.sql.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            pst = con1.prepareStatement("select  * from dikigoros where eidikotita=?  ");
             pst.setString(1, dikaio);
           ResultSet rs = pst.executeQuery();
           ResultSetMetaData Rss = rs.getMetaData();
           c = Rss.getColumnCount();
           
           DefaultTableModel Df = (DefaultTableModel)Lista_Dikigorwn.getModel();
           Df.setRowCount(0);
           
           while(rs.next())
           {
               Vector v2 = new Vector();
               
               for(int a=1; a<=c; a++)
               {
                 v2.add(rs.getString("id_dik"));
                   v2.add(rs.getString("epwnimo_dik"));
                       v2.add(rs.getString("onoma_dik"));
                         
                   }
              Df.addRow(v2);
                }
         } 
          catch (ClassNotFoundException ex) {
            Logger.getLogger(Lista_Dikigorwn.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger(Lista_Dikigorwn.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }//GEN-LAST:event_GetListaDikMouseClicked

      private void table_update()
    {
        int c;
          String dikaio = (String)jComboBox1.getSelectedItem().toString();
           try {
            Class.forName("java.sql.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            pst = con1.prepareStatement("select * from dikigoros where eidikotita=?   ");
            pst.setString(1, dikaio);
            
           ResultSet rs = pst.executeQuery();
           ResultSetMetaData Rss = rs.getMetaData();
           c = Rss.getColumnCount();
           
           DefaultTableModel Df = (DefaultTableModel)Lista_Dikigorwn.getModel();
           Df.setRowCount(0);
           
           
           while(rs.next())
           {
               Vector v2 = new Vector();
               
               for(int a=1; a<=c; a++)
               {
                
                   v2.add(rs.getString("id_dik"));
                       v2.add(rs.getString("epwnimo_dik"));
                           v2.add(rs.getString("onoma_dik"));
                               
                   }
              Df.addRow(v2);
               
           }
         
                 
            
        
        } 
           
               
         catch (ClassNotFoundException ex) {
            Logger.getLogger(Lista_Dikigorwn.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger(Lista_Dikigorwn.class.getName()).log(Level.SEVERE, null, ex);
         } 
           
      }
    
    
    
    
    private void DeleteDikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteDikMouseClicked
         DefaultTableModel Df = (DefaultTableModel) Lista_Dikigorwn.getModel();
         int selectedIndex =  Lista_Dikigorwn.getSelectedRow();
         
          try {
             
              int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
            
            
        
             Class.forName("java.sql.Driver");
             
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            pst = con1.prepareStatement("delete from dikigoros where id_dik=? ");
            
            pst.setInt(1,id );
            
            pst.executeUpdate();
            
           JOptionPane.showMessageDialog(this,"Ο Δικηγόρος διαγράφηκε");
            
            table_update(); 
            
            
         
          }   
               
         catch (ClassNotFoundException ex) {
            Logger.getLogger(Lista_Dikigorwn.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger(Lista_Dikigorwn.class.getName()).log(Level.SEVERE, null, ex);
         } 
    }//GEN-LAST:event_DeleteDikMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
     DefaultTableModel Df = (DefaultTableModel) Lista_Dikigorwn.getModel();
         int selectedIndex =  Lista_Dikigorwn.getSelectedRow();  
          int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
          this.dispose();
         PliroforiesDik m = new  PliroforiesDik(id);
        m.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        DefaultTableModel Df = (DefaultTableModel) Lista_Dikigorwn.getModel();
         int selectedIndex =  Lista_Dikigorwn.getSelectedRow();
          
         try {
             
              int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
            
            
        
             Class.forName("java.sql.Driver");
             
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            pst = con1.prepareStatement("select * from dikigoros where id_dik=? ");
            
            pst.setInt(1,id );
            
            rs = pst.executeQuery();
              
            while(rs.next())
           {
               
               dikigoros.setText(rs.getString("username_dikigoros"));
               dikigoros.setVisible(false);
           }
          }   
               
         catch (ClassNotFoundException ex) {
            Logger.getLogger(Lista_Dikigorwn.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger(Lista_Dikigorwn.class.getName()).log(Level.SEVERE, null, ex);
         } 
          try {
             
             Class.forName("java.sql.Driver");
             
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            pst = con1.prepareStatement("select count(*) as counter from ypothesi inner join ekvasi on ar_prwtokollou=ar_prwtokollou_e  where yp_dik=? and ekvasi_yp='Θετική' ");
            
            pst.setString(1,dikigoros.getText() );
            
             rs = pst.executeQuery();
              
            while(rs.next())
           {
            check.setText(rs.getString("counter"));
            check.setVisible(false);
           }
          }   
         catch (ClassNotFoundException ex) {
            Logger.getLogger(Lista_Dikigorwn.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger(Lista_Dikigorwn.class.getName()).log(Level.SEVERE, null, ex);
         } 
          int epitixies = Integer.parseInt(check.getText());
          if (epitixies>=3)
          {
           JOptionPane.showMessageDialog(this,"Ο Δικηγόρος δικαιούται το Bonus");   
          }
          else
          {
              JOptionPane.showMessageDialog(this,"Ο Δικηγόρος δεν δικαιούται το Bonus");  
          }
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lista_Dikigorwn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lista_Dikigorwn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lista_Dikigorwn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lista_Dikigorwn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lista_Dikigorwn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteDik;
    private javax.swing.JLabel GetListaDik;
    private javax.swing.JTable Lista_Dikigorwn;
    private javax.swing.JLabel check;
    private javax.swing.JLabel dikigoros;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
