/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.laywer1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ΜΑΡΙΝΟΣ
 */
public class PliroforiesPel extends javax.swing.JFrame {
Connection con1 ;
        PreparedStatement pst;
        ResultSet rs;
    int  mousepX,mousepY;
    public PliroforiesPel(String pelatis) {
        initComponents();
        user.setText(pelatis);
       user.setVisible(false);
       getPlirofPel();
    }

    private void getPlirofPel()
    {
       
         String pelatis=user.getText();
           try {
            Class.forName("java.sql.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            pst = con1.prepareStatement("select * from pelatis where username_pelatis=? ");
            pst.setString(1, pelatis);
            
            
            rs = pst.executeQuery();
              
            while(rs.next())
           {
            onoma_pel.setText(rs.getString("onoma_pel"));
           epwnimo_pel.setText(rs.getString("epwnimo_pel"));
          txt_email.setText(rs.getString("email"));
          txt_phone.setText(rs.getString("tel"));
          txt_poli.setText(rs.getString("city"));
           txt_street.setText(rs.getString("street"));
           txt_afm.setText(rs.getString("afm"));
           txt_username.setText(rs.getString("username_pelatis"));
         txt_password.setText(rs.getString("password_pelatis"));
           }
        
           
           
           
          
           }
         
                 
            
        
        
           
               
         catch (ClassNotFoundException ex) {
            Logger.getLogger(PliroforiesPel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger(PliroforiesPel.class.getName()).log(Level.SEVERE, null, ex);
         } 
           
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        onoma_pel = new javax.swing.JLabel();
        epwnimo_pel = new javax.swing.JLabel();
        txt_email = new javax.swing.JLabel();
        txt_phone = new javax.swing.JLabel();
        txt_poli = new javax.swing.JLabel();
        txt_street = new javax.swing.JLabel();
        txt_afm = new javax.swing.JLabel();
        txt_username = new javax.swing.JLabel();
        txt_password = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("E-LAWYER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Επώνυμο:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Τηλέφωνο:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Όνομα:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Username: ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 120, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Email:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Πόλη:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Διεύθυνση:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ΑΦΜ:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 90, 40));

        onoma_pel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        onoma_pel.setForeground(new java.awt.Color(204, 204, 204));
        onoma_pel.setText(" ");
        jPanel1.add(onoma_pel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, 30));

        epwnimo_pel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        epwnimo_pel.setForeground(new java.awt.Color(204, 204, 204));
        epwnimo_pel.setText(" ");
        jPanel1.add(epwnimo_pel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 180, 40));

        txt_email.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_email.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 190, 40));

        txt_phone.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_phone.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 180, 40));

        txt_poli.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_poli.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txt_poli, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 220, 50));

        txt_street.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_street.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txt_street, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 170, 40));

        txt_afm.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_afm.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txt_afm, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 170, 40));

        txt_username.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_username.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 170, 40));

        txt_password.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_password.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 140, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/icons8_delete_50px_1.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
         int aX = evt.getXOnScreen();
        int aY = evt.getYOnScreen();
        
        this.setLocation(aX-mousepX,aY-mousepY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
           mousepX = evt.getX();
         mousepY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PliroforiesPel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PliroforiesPel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PliroforiesPel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PliroforiesPel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PliroforiesPel("user").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel epwnimo_pel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel onoma_pel;
    private javax.swing.JLabel txt_afm;
    private javax.swing.JLabel txt_email;
    private javax.swing.JLabel txt_password;
    private javax.swing.JLabel txt_phone;
    private javax.swing.JLabel txt_poli;
    private javax.swing.JLabel txt_street;
    private javax.swing.JLabel txt_username;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
