/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.laywer1;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.JFileChooser ;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

public class Trexoumenes_Yp extends javax.swing.JFrame {
 Connection con1 ;
        PreparedStatement pst;
        ResultSet rs;
        
    int  mousepX,mousepY;
    public Trexoumenes_Yp() {
        initComponents();
        getListaTrexYp();
    }

   private void getListaTrexYp()
   {
    int c;
     try {
            Class.forName("java.sql.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            pst = con1.prepareStatement("select * from ypothesi where katastasi='Ενεργή' ");
            
           ResultSet rs = pst.executeQuery();
           ResultSetMetaData Rss = rs.getMetaData();
           c = Rss.getColumnCount();
           
           DefaultTableModel Df = (DefaultTableModel)Trexoumenes_Yp.getModel();
           Df.setRowCount(0);
           
           while(rs.next())
           {
               Vector v2 = new Vector();
               
               for(int a=1; a<=c; a++)
               {
                v2.add(rs.getString("ar_prwtokollou"));
                   v2.add(rs.getString("yp_dik"));
                       v2.add(rs.getString("dikaio"));
                           v2.add(rs.getString("imerominia"));
                   }
              Df.addRow(v2);
                }
         } 
          catch (ClassNotFoundException ex) {
            Logger.getLogger(Trexoumenes_Yp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger(Trexoumenes_Yp.class.getName()).log(Level.SEVERE, null, ex);
         }
    
    
    
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        getplirofYp = new javax.swing.JButton();
        ChangeCondition = new javax.swing.JButton();
        apoint_Dik = new javax.swing.JButton();
        UploadArxeio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Trexoumenes_Yp = new javax.swing.JTable();
        CByp_dik = new javax.swing.JComboBox<>();
        txtimerominia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        katastasi = new javax.swing.JLabel();
        CBkatastasi = new javax.swing.JComboBox<>();
        CBekvasi = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("E-LAWYER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/icons8_back_arrow_50px_2.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 460, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/icons8_exit_50px.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/Logo-3.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, -1, 240));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Τρεχούμενες Υποθέσεις");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        getplirofYp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getplirofYp.setText("Πληροφορίες");
        getplirofYp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getplirofYpMouseClicked(evt);
            }
        });
        getplirofYp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getplirofYpActionPerformed(evt);
            }
        });
        jPanel1.add(getplirofYp, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 150, 40));

        ChangeCondition.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ChangeCondition.setText("Επεξεργασία");
        ChangeCondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeConditionActionPerformed(evt);
            }
        });
        jPanel1.add(ChangeCondition, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, 40));

        apoint_Dik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        apoint_Dik.setText("Αλλαγή Υπ. Δικηγόρου");
        apoint_Dik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apoint_DikActionPerformed(evt);
            }
        });
        jPanel1.add(apoint_Dik, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, 210, 40));

        UploadArxeio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UploadArxeio.setText("Upload");
        UploadArxeio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UploadArxeioMouseClicked(evt);
            }
        });
        UploadArxeio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadArxeioActionPerformed(evt);
            }
        });
        jPanel1.add(UploadArxeio, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, -1, 40));

        Trexoumenes_Yp.setAutoCreateRowSorter(true);
        Trexoumenes_Yp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Αριθμός Πρωτοκόλλου", "Υπ. Δικηγόρος", "Δίκαιο", "Ημ/μηνία Δίκης"
            }
        ));
        Trexoumenes_Yp.setSelectionBackground(new java.awt.Color(0, 51, 204));
        Trexoumenes_Yp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Trexoumenes_YpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Trexoumenes_Yp);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 500, 270));

        CByp_dik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Χωρίς Επιλογή" }));
        CByp_dik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CByp_dikMouseClicked(evt);
            }
        });
        jPanel1.add(CByp_dik, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, 210, 30));

        txtimerominia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtimerominia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 140, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Y-M-D:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 30));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Έκβαση:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, 30));

        katastasi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        katastasi.setForeground(new java.awt.Color(255, 255, 255));
        katastasi.setText("Κατάσταση:");
        jPanel2.add(katastasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        CBkatastasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Χωρίς Επιλογή", "Ολοκληρωμένη" }));
        jPanel2.add(CBkatastasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 210, 30));

        CBekvasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Χωρίς Επιλογή", "Θετική", "Αρνητική" }));
        jPanel2.add(CBekvasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 210, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 250, 180));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
         int aX = evt.getXOnScreen();
        int aY = evt.getYOnScreen();
        
        this.setLocation(aX-mousepX,aY-mousepY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
           mousepX = evt.getX();
         mousepY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
       this.dispose();
        Dikigoriko_Grafeio m = new Dikigoriko_Grafeio();
        m.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void getplirofYpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getplirofYpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getplirofYpActionPerformed

    private void apoint_DikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apoint_DikActionPerformed
       DefaultTableModel Df = (DefaultTableModel)Trexoumenes_Yp.getModel();
         int selectedIndex = Trexoumenes_Yp.getSelectedRow();
         DefaultComboBoxModel model = null;
         
         
         
          try {
              int ar_ptr= Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
            
             
           String dikigoros = CByp_dik.getSelectedItem().toString();
            
            
             if ( dikigoros.equals("Χωρίς Επιλογή"))
            {
             JOptionPane.showMessageDialog(null,"Επιλέξτε Δικηγόρο","Error",JOptionPane.ERROR_MESSAGE);
            
            }
             if(!dikigoros.equals("Χωρίς Επιλογή")) {
             Class.forName("java.sql.Driver");
             
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            pst= con1.prepareStatement("update ypothesi set yp_dik= ? where ar_prwtokollou=?");
            pst.setString(1, dikigoros);
           pst.setInt(1,ar_ptr );
         
            
            
            pst.executeUpdate();
            
           JOptionPane.showMessageDialog(this,"Η υπόθεση ενημερώθηκε");
            
           getListaTrexYp();
            
            txtimerominia.setText("");
            CBkatastasi.setModel(model);
            
        } 
          }   
               
         catch (ClassNotFoundException ex) {
            Logger.getLogger( Trexoumenes_Yp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger( Trexoumenes_Yp.class.getName()).log(Level.SEVERE, null, ex);
         } 
    }//GEN-LAST:event_apoint_DikActionPerformed

    private void ChangeConditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeConditionActionPerformed
         DefaultTableModel Df = (DefaultTableModel)Trexoumenes_Yp.getModel();
         int selectedIndex = Trexoumenes_Yp.getSelectedRow();
         DefaultComboBoxModel model = null;
         
         
         
          try {
              int ar_ptr= Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
            
              
            String imerominia = txtimerominia.getText();
           String katastasi = CBkatastasi.getSelectedItem().toString();
           String ekvasi = CBekvasi.getSelectedItem().toString();
           if (!imerominia.equals("") &  !katastasi.equals("Χωρίς Επιλογή")&  !ekvasi.equals("Χωρίς Επιλογή"))
            {
             JOptionPane.showMessageDialog(null,"Δεν μπορεί να γίνει η αλλαγή ","Error",JOptionPane.ERROR_MESSAGE);
            
            }
            
             if (imerominia.equals("") &  katastasi.equals("Χωρίς Επιλογή") &  ekvasi.equals("Χωρίς Επιλογή"))
            {
             JOptionPane.showMessageDialog(null,"Συμπληρώστε τα Στοιχεία Αλλαγής","Error",JOptionPane.ERROR_MESSAGE);
            
            }
             if (!imerominia.equals("") &  katastasi.equals("Χωρίς Επιλογή") &  ekvasi.equals("Χωρίς Επιλογή"))
             {
             Class.forName("java.sql.Driver");
             
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            pst= con1.prepareStatement("update ypothesi set imerominia= ? where ar_prwtokollou=?");
            pst.setString(1, imerominia);
             pst.setInt(2,ar_ptr );
            
            
            pst.executeUpdate();
            
           JOptionPane.showMessageDialog(this,"Η ημερομηνία άλλαξε");
            
           getListaTrexYp();
            
            txtimerominia.setText("");
            CBkatastasi.setModel(model);
            
       } 
            if (imerominia.equals("") &  !katastasi.equals("Χωρίς Επιλογή") & !ekvasi.equals("Χωρίς Επιλογή"))
             {
             Class.forName("java.sql.Driver");
             
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            pst= con1.prepareStatement("update ypothesi set katastasi= ? where ar_prwtokollou=?");
            pst.setString(1, katastasi);
             pst.setInt(2,ar_ptr );
            
            
            pst.executeUpdate();
            Class.forName("java.sql.Driver");
             
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            pst= con1.prepareStatement("insert into ekvasi (ar_prwtokollou_e,ekvasi_yp) values (?,?)");
             pst.setInt(1,ar_ptr );
             pst.setString(2, ekvasi);
            
            pst.executeUpdate();
           JOptionPane.showMessageDialog(this,"Η Κατάσταση άλλαξε");
            
           getListaTrexYp();
            
            txtimerominia.setText("");
            CBkatastasi.setModel(model);
            CBekvasi.setModel(model);
       } 
          }      
         catch (ClassNotFoundException ex) {
            Logger.getLogger( Trexoumenes_Yp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger( Trexoumenes_Yp.class.getName()).log(Level.SEVERE, null, ex);
         } 
          
    }//GEN-LAST:event_ChangeConditionActionPerformed

    private void UploadArxeioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UploadArxeioMouseClicked
      DefaultTableModel Df = (DefaultTableModel) Trexoumenes_Yp.getModel();
         int selectedIndex =  Trexoumenes_Yp.getSelectedRow();
        
        JFileChooser chooser = new JFileChooser();
    chooser.showOpenDialog(null);
    File f=chooser.getSelectedFile();
    filename=f.getAbsolutePath();
    
    try{
    File pdf=new File(filename);
    FileInputStream fis=new FileInputStream(pdf);
    ByteArrayOutputStream bos=new ByteArrayOutputStream();
    byte[] buf=new byte[2048];
    for(int readNum; (readNum=fis.read(buf))!=-1;){
     bos.write(buf,0,readNum);   
    }
    arxeio=bos.toByteArray();
    
    }
    
    
    catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    }
     try {
           int ar_prt = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
            Class.forName("java.sql.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            pst = con1.prepareStatement("insert into uliko values(?,?)");
            pst.setInt(1,ar_prt );
            pst.setBytes(2, arxeio);
    
            pst.execute();
            JOptionPane.showMessageDialog(null, "Το αρχείο ανέβηκε!");
            pst.close();
     }
     catch(Exception e){
     JOptionPane.showMessageDialog(null,e);
     }
     
    
    
    }//GEN-LAST:event_UploadArxeioMouseClicked

    private void UploadArxeioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadArxeioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UploadArxeioActionPerformed

    private void Trexoumenes_YpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Trexoumenes_YpMouseClicked
       DefaultTableModel Df = (DefaultTableModel)Trexoumenes_Yp.getModel();
         int selectedIndex = Trexoumenes_Yp.getSelectedRow();
          DefaultComboBoxModel model = null;
        String dikaio = Trexoumenes_Yp.getModel().getValueAt(selectedIndex, 2).toString();
        
          try {
              
            Class.forName("java.sql.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            pst = con1.prepareStatement("select * from dikigoros where eidikotita=? ");
            pst.setString(1,dikaio);
             ResultSet rs = pst.executeQuery();
               while(rs.next())
           {
              CByp_dik.addItem(rs.getString("username_dikigoros")); 
           }
    }                                     
catch (ClassNotFoundException ex) {
            Logger.getLogger(Trexoumenes_Yp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger(Trexoumenes_Yp.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_Trexoumenes_YpMouseClicked

    private void CByp_dikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CByp_dikMouseClicked
        
    }//GEN-LAST:event_CByp_dikMouseClicked

    private void getplirofYpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getplirofYpMouseClicked
 DefaultTableModel Df = (DefaultTableModel)Trexoumenes_Yp.getModel();
         int selectedIndex =  Trexoumenes_Yp.getSelectedRow();  
          int ar_ptr = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
         
         PliroforiesYp m = new  PliroforiesYp(ar_ptr);
        m.setVisible(true);
    }//GEN-LAST:event_getplirofYpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trexoumenes_Yp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trexoumenes_Yp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trexoumenes_Yp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trexoumenes_Yp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trexoumenes_Yp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBekvasi;
    private javax.swing.JComboBox<String> CBkatastasi;
    private javax.swing.JComboBox<String> CByp_dik;
    private javax.swing.JButton ChangeCondition;
    private javax.swing.JTable Trexoumenes_Yp;
    private javax.swing.JButton UploadArxeio;
    private javax.swing.JButton apoint_Dik;
    private javax.swing.JButton getplirofYp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel katastasi;
    private javax.swing.JTextField txtimerominia;
    // End of variables declaration//GEN-END:variables
byte[] arxeio=null;
String filename=null;

}
