/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.laywer1;

/**
 *
 * @author ΜΑΡΙΝΟΣ
 */
public class Dikigoriko_Grafeio extends javax.swing.JFrame {

    int  mousepX,mousepY;
    public Dikigoriko_Grafeio() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AddCase = new javax.swing.JLabel();
        Trexoumenes_Yp = new javax.swing.JLabel();
        Mi_Energes_Yp = new javax.swing.JLabel();
        Lista_Dik = new javax.swing.JLabel();
        Epikoinwnia = new javax.swing.JLabel();
        Diathesimes_formes = new javax.swing.JLabel();
        ListaPelatwn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/icons8_back_arrow_50px_2.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/icons8_exit_50px.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/Logo-3.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 220, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ΜΕΝΟΥ ΔΙΚΗΓΟΡΙΚΟΥ ΓΡΑΦΕΊΟΥ:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 430, 50));

        AddCase.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        AddCase.setForeground(new java.awt.Color(255, 255, 255));
        AddCase.setText("1) Δημιουργία Υπόθεσης");
        AddCase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddCaseMouseClicked(evt);
            }
        });
        jPanel1.add(AddCase, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 310, 40));

        Trexoumenes_Yp.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Trexoumenes_Yp.setForeground(new java.awt.Color(255, 255, 255));
        Trexoumenes_Yp.setText("2) Τρεχούμενες Υποθέσεις");
        Trexoumenes_Yp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Trexoumenes_YpMouseClicked(evt);
            }
        });
        jPanel1.add(Trexoumenes_Yp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 280, 30));

        Mi_Energes_Yp.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Mi_Energes_Yp.setForeground(new java.awt.Color(255, 255, 255));
        Mi_Energes_Yp.setText("5) Μη Ενεργές Υποθέσεις");
        Mi_Energes_Yp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mi_Energes_YpMouseClicked(evt);
            }
        });
        jPanel1.add(Mi_Energes_Yp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 450, 40));

        Lista_Dik.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Lista_Dik.setForeground(new java.awt.Color(255, 255, 255));
        Lista_Dik.setText("3) Λίστα Δικηγόρων");
        Lista_Dik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lista_DikMouseClicked(evt);
            }
        });
        jPanel1.add(Lista_Dik, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 430, 40));

        Epikoinwnia.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Epikoinwnia.setForeground(new java.awt.Color(255, 255, 255));
        Epikoinwnia.setText("7) Επικοινωνία");
        Epikoinwnia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EpikoinwniaMouseClicked(evt);
            }
        });
        jPanel1.add(Epikoinwnia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 190, 40));

        Diathesimes_formes.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Diathesimes_formes.setForeground(new java.awt.Color(255, 255, 255));
        Diathesimes_formes.setText("6) Διαθέσιμες Φόρμες και Στοιχεία Υποψήφιων Πελατών");
        Diathesimes_formes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Diathesimes_formesMouseClicked(evt);
            }
        });
        jPanel1.add(Diathesimes_formes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        ListaPelatwn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ListaPelatwn.setForeground(new java.awt.Color(255, 255, 255));
        ListaPelatwn.setText("4) Λίστα Πελατών");
        ListaPelatwn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaPelatwnMouseClicked(evt);
            }
        });
        jPanel1.add(ListaPelatwn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
         int aX = evt.getXOnScreen();
        int aY = evt.getYOnScreen();
        
        this.setLocation(aX-mousepX,aY-mousepY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
           mousepX = evt.getX();
         mousepY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        this.dispose();
        Login_Page m = new Login_Page();
        m.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void AddCaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddCaseMouseClicked
         this.dispose();
        Create_Yp m = new Create_Yp();
        m.setVisible(true);
    }//GEN-LAST:event_AddCaseMouseClicked

    private void ListaPelatwnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaPelatwnMouseClicked
         this.dispose();
        Lista_Pelatwn m = new Lista_Pelatwn();
        m.setVisible(true);
    }//GEN-LAST:event_ListaPelatwnMouseClicked

    private void Lista_DikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lista_DikMouseClicked
         this.dispose();
        Lista_Dikigorwn m = new Lista_Dikigorwn();
        m.setVisible(true);
    }//GEN-LAST:event_Lista_DikMouseClicked

    private void Trexoumenes_YpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Trexoumenes_YpMouseClicked
       this.dispose();
        Trexoumenes_Yp m = new Trexoumenes_Yp();
        m.setVisible(true);
    }//GEN-LAST:event_Trexoumenes_YpMouseClicked

    private void Mi_Energes_YpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mi_Energes_YpMouseClicked
         this.dispose();
        Mi_Energes_Yp m = new Mi_Energes_Yp("user");
        m.setVisible(true);
    }//GEN-LAST:event_Mi_Energes_YpMouseClicked

    private void Diathesimes_formesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Diathesimes_formesMouseClicked
        this.dispose();
        Diathesimes_Formes m = new Diathesimes_Formes();
        m.setVisible(true);
    }//GEN-LAST:event_Diathesimes_formesMouseClicked

    private void EpikoinwniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EpikoinwniaMouseClicked
        this.dispose();
        Epikoinonia m = new Epikoinonia();
        m.setVisible(true);
    }//GEN-LAST:event_EpikoinwniaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dikigoriko_Grafeio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dikigoriko_Grafeio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dikigoriko_Grafeio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dikigoriko_Grafeio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dikigoriko_Grafeio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddCase;
    private javax.swing.JLabel Diathesimes_formes;
    private javax.swing.JLabel Epikoinwnia;
    private javax.swing.JLabel ListaPelatwn;
    private javax.swing.JLabel Lista_Dik;
    private javax.swing.JLabel Mi_Energes_Yp;
    private javax.swing.JLabel Trexoumenes_Yp;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
