/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.laywer1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ΜΑΡΙΝΟΣ
 */
public class Mi_Energes_Yp extends javax.swing.JFrame {
Connection con1 ;
        PreparedStatement pst;
        ResultSet rs;
    int  mousepX,mousepY;
    public Mi_Energes_Yp(String username) {
        initComponents();
       user.setText(username);
       user.setVisible(false); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        getPlirofYp = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista_Pelatwn = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        CBdikaio = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        CBetos = new javax.swing.JComboBox<>();
        getListaMiEnergwnYp = new javax.swing.JLabel();
        user = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("E-LAWYER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/icons8_back_arrow_50px_2.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 490, -1, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/icons8_exit_50px.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/Logo-3.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, 240));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Μη Ενεργές Υποθέσεις");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        getPlirofYp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getPlirofYp.setText("Πληροφορίες");
        getPlirofYp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPlirofYpActionPerformed(evt);
            }
        });
        jPanel1.add(getPlirofYp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 150, 40));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Download");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, -1, 40));

        Lista_Pelatwn.setAutoCreateRowSorter(true);
        Lista_Pelatwn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Αριθμός Πρωτοκόλλου", "Υπ. Δικηγόρος", "Ημ/μηνία Δίκης"
            }
        ));
        Lista_Pelatwn.setSelectionBackground(new java.awt.Color(255, 255, 153));
        jScrollPane1.setViewportView(Lista_Pelatwn);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 480, 200));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Αναζήτηση Ανά Δίκαιο:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        CBdikaio.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CBdikaio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Χωρίς Επιλογή", "Εμπορικό" }));
        jPanel1.add(CBdikaio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Αναζήτηση Ανά Έτος:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        CBetos.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CBetos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Χωρίς Επιλογή", "2020", "2019", "2018" }));
        CBetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBetosActionPerformed(evt);
            }
        });
        jPanel1.add(CBetos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        getListaMiEnergwnYp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/laywer1/icons8_search_40px.png"))); // NOI18N
        getListaMiEnergwnYp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getListaMiEnergwnYpMouseClicked(evt);
            }
        });
        jPanel1.add(getListaMiEnergwnYp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 30, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
         int aX = evt.getXOnScreen();
        int aY = evt.getYOnScreen();
        
        this.setLocation(aX-mousepX,aY-mousepY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
           mousepX = evt.getX();
         mousepY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
     
        try {
            Class.forName("com.mysql.jdbc.Driver");
        con1=DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
        pst=con1.prepareStatement("select * from dikigoros where username_dikigoros=? ");
        pst.setString(1, user.getText());
        rs=pst.executeQuery();
        
    if (rs.next())
    {
  
        Dikigoros m = new Dikigoros(user.getText());
        m.setVisible(true);
         this.dispose();
    }
    else{
       this.dispose();
        Dikigoriko_Grafeio m = new Dikigoriko_Grafeio();
        m.setVisible(true);  
        
    }
    } catch (SQLException ex) {
            Logger.getLogger(Mi_Energes_Yp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
         Logger.getLogger(Mi_Energes_Yp.class.getName()).log(Level.SEVERE, null, ex);
     }
        
        
        this.dispose();
        Dikigoriko_Grafeio m = new Dikigoriko_Grafeio();
        m.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void getPlirofYpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPlirofYpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getPlirofYpActionPerformed

    private void CBetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBetosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBetosActionPerformed

    private void getListaMiEnergwnYpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getListaMiEnergwnYpMouseClicked
       int c;
        String dikaio =CBdikaio.getSelectedItem().toString();
           String etos = CBetos.getSelectedItem().toString();
         
           try {
             if (dikaio.equals("Χωρίς Επιλογή") &  etos.equals("Χωρίς Επιλογή"))
            {
             JOptionPane.showMessageDialog(null,"Λάθος Στοιχεία","Error",JOptionPane.ERROR_MESSAGE);
            
            }
             if (dikaio.equals("Χωρίς Επιλογή")) 
             {
             Class.forName("java.sql.Driver");
             
          con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            pst = con1.prepareStatement("select * from ypothesi where imerominia like '%?' and katastasi='Ολοκληρωμένη' ");
          pst.setString(1, etos);
            
           ResultSet rs = pst.executeQuery();
           ResultSetMetaData Rss = rs.getMetaData();
           c = Rss.getColumnCount();
           
           DefaultTableModel Df = (DefaultTableModel)Lista_Pelatwn.getModel();
           Df.setRowCount(0);
           
           while(rs.next())
           {
               Vector v2 = new Vector();
               
               for(int a=1; a<=c; a++)
               {
                v2.add(rs.getString("ar_prwtokollou"));
                   v2.add(rs.getString("yp_dik"));
                       v2.add(rs.getString("imerominia"));
                          
                   }
              Df.addRow(v2);
                }
             }
             
               if (etos.equals("Χωρίς Επιλογή")) 
             {
             Class.forName("java.sql.Driver");
             
          con1 = DriverManager.getConnection("jdbc:mysql://localhost/e_lawyer?useUnicode=yes&characterEncoding=UTF-8","root","");
            pst = con1.prepareStatement("select * from ypothesi where dikaio = ? and katastasi='Ολοκληρωμένη' ");
          pst.setString(1, dikaio);
            
           ResultSet rs = pst.executeQuery();
           ResultSetMetaData Rss = rs.getMetaData();
           c = Rss.getColumnCount();
           
           DefaultTableModel Df = (DefaultTableModel)Lista_Pelatwn.getModel();
           Df.setRowCount(0);
           
           while(rs.next())
           {
               Vector v2 = new Vector();
               
               for(int a=1; a<=c; a++)
               {
                v2.add(rs.getString("ar_prwtokollou"));
                   v2.add(rs.getString("yp_dik"));
                       v2.add(rs.getString("imerominia"));
                          
                   }
              Df.addRow(v2);
                }
             } 
           }
               
         catch (ClassNotFoundException ex) {
            Logger.getLogger( Mi_Energes_Yp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger( Trexoumenes_Yp.class.getName()).log(Level.SEVERE, null, ex);
                }
        
    }//GEN-LAST:event_getListaMiEnergwnYpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mi_Energes_Yp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mi_Energes_Yp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mi_Energes_Yp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mi_Energes_Yp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
  

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mi_Energes_Yp("user").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBdikaio;
    private javax.swing.JComboBox<String> CBetos;
    private javax.swing.JTable Lista_Pelatwn;
    private javax.swing.JLabel getListaMiEnergwnYp;
    private javax.swing.JButton getPlirofYp;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
